### ISSUE TITLE
index.js file name

### ISSUE THREAD

**Issue by jbesraa** [fac-u/take-me-away#42]
its not clear its the server.start file

**Comment by stevehopkinson** [comment]
Hi @esraajb - naming the file index.js is actually standard node naming convention: http://stackoverflow.com/questions/21063587/what-is-index-js-typically-used-for-in-node-js-projects

'In Node.js, Node itself is the web server so you don't need to name anything index.js but it's easier for people to understand which file to run first.

index.js typically handles your app startup, routing and other functions of your application and does require other modules to add functionality. If you're running a website or web app it would also handle become a basic HTTP web server replacing the role of something more traditional like Apache.'

**Comment by jsms90** [comment]
More of a issue with having no readme than anything else
