### ISSUE TITLE
Slightly confusing order for your functions

### ISSUE THREAD

**Issue by otajor** [fac-u/take-me-away#46]
[Here](https://github.com/fac-u/take-me-away/blob/master/src/server.js#L40-L41) you are calling functions that you only declare later in the file. 

Hoisting means that this works fine, but I find it bit counterintuitive to read - why not just have the functions declared in the order that they're used?

**Comment by msmichellegar** [comment]
I agree. I think it would make more sense to call the functions after they've been declared. Better still, declare the functions in another file and require them in.

**Comment by stevehopkinson** [comment]
We've modularised all of the code now, so this should no longer be an issue.
