### ISSUE TITLE
Error handling

### ISSUE THREAD

**Issue by otajor** [fac-u/take-me-away#52]
You're passing your errors back to your callbacks nicely but you don't seem to be doing anything with them? Functions like [processWeather](https://github.com/fac-u/take-me-away/blob/master/src/server.js#L54) take an error parameter but then just ignore it.

Also when you're passing your error back [here](https://github.com/fac-u/take-me-away/blob/master/src/server.js#L46-L48) you might want to pass something useful back to the callback in the case of a bad status code. 
```javascript
if (err || response.statusCode !== 200) {
  cb(err);
 } else {
  ...
```
If there is no error but the statusCode is something other than 200, the callback will just be passed `undefined` as an error, which is falsy - so the callback would think there was no error.

**Comment by stevehopkinson** [comment]
Fixed now. Ta!
